#pragma once
#include "Registers.h"

enum ProcessState
{
	NEW_STATE,
	RUNNING_STATE,
	WAITING_STATE,
	READY_STATE,
	TERMINATED_STATE
};

enum PriorityClass
{
	IDLE_PRIORITY_CLASS = 1,
	LOW_PRIORITY_CLASS = 2,
	BELOW_NORMAL_PRIORITY_CLASS = 3,
	NORMAL_PRIORITY_CLASS = 4,
	ABOVE_NORMAL_PRIORITY_CLASS = 5,
	HIGH_PRIORITY_CLASS = 6,
	ULTRA_HIGH_PRIORITY_CLASS = 7,
	MAX_PRIORITY_CLASS = 8
};